import "../styles/globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        
        <Header />

        <div className="max-w-[800px] mx-auto"> 
          {children} 
        </div>

      </body>
    </html>
  )
}